ALTER TABLE users
ADD COLUMN salary INT;

ALTER TABLE users
MODIFY COLUMN name VARCHAR(250);

ALTER TABLE users
MODIFY COLUMN gender VARCHAR(150);

ALTER TABLE users
MODIFY COLUMN email VARCHAR(100) AFTER id;

ALTER TABLE users
MODIFY COLUMN name VARCHAR(250) AFTER id;


ALTER TABLE users
ADD COLUMN PF BOOLEAN DEFAULT TRUE;


ALTER TABLE users
DROP COLUMN PF;
SELECT*FROM users